- name: Install build host packages
  apt:
    autoclean: true
    purge: true
    install_recommends: false
    update_cache: true
    pkg:
    - git
    - tar
    - make
    - gcc
    - gawk
    - wget
    - git
    - diffstat
    - unzip
    - texinfo
    - gcc
    - build-essential
    - chrpath
    - socat
    - cpio
    - python3
    - python3-pip
    - python3-pexpect
    - xz-utils
    - debianutils
    - iputils-ping
    - python3-git
    - python3-jinja2
    - libegl1-mesa
    - libsdl1.2-dev
    - pylint3
    - xterm
    - python3-subunit
    - mesa-common-dev
    - zstd
    - liblz4-tool

- name: Configure system
  shell: |
    localectl set-locale LANG=en_US.UTF-8

- name: Clone poky
  shell: | 
    if [ -d {{ yocto_dir }} ]; then
        cd {{ yocto_dir }}
        git pull;
    else
        git clone git://git.yoctoproject.org/poky {{ yocto_dir }};
    fi

- name: Clone bb repo (yocto navigation tool)
  shell:  |
    if [ -d {{ bb_dir }} ]; then
      cd {{ bb_dir }}
      git pull;
    else
      git clone https://github.com/kergoth/bb.git {{ bb_dir }};
    fi

# Credit to keithel/yocto-vagrant
- name: Add bb to PATH
  lineinfile:
    dest=/home/vagrant/.profile
    line='PATH="{{ bb_dir }}/bb/bin:$PATH"'
    regexp='^PATH="{{ bb_dir }}/bb/bin'
    owner=vagrant
    state=present
    insertafter=EOF
    create=True

- name: Setup directory permissions
  shell: |
    chown -R vagrant /home/vagrant