Vagrant.configure("2") do |config|
    config.vm.define :yocto_vm do |yocto_vm|
        yocto_vm.vm.box = "debian/bullseye64"
        yocto_vm.vm.hostname = "yoctobox"
        config.vm.disk :disk, size: ENV['BOX_SIZE'] || "140GB", primary: true
    end

    config.vm.provision :ansible do |ansi|
      ansi.playbook = "../ansible/playbook.yml"
      ansi.extra_vars = { ansible_user: 'vagrant' }
    end

    config.vm.provider "libvirt" do |libv|
        libv.memory = ENV['BOX_MEMORY'] || 4096
        libv.cpus = ENV['BOX_CPUS'] || 6
        libv.machine_virtual_size = ENV['BOX_SIZE'] || 140
    end 

    config.vm.provider "virtualbox" do |vbox|
        vbox.linked_clone = true
        vbox.memory = ENV['BOX_MEMORY'] || 4096
        vbox.cpus = ENV['BOX_CPUS'] || 6
        vbox.customize ["modifyvm", :id, "--cpuexecutioncap", "50"]
        vbox.gui = false
        vbox.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
    end
end
